# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
          enum: string
          set: string
          varbinary: string
          tinyblob: text
          bit: smallint
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
            auto_generate_proxy_classes: "%kernel.debug%"
            auto_mapping: true
            naming_strategy: doctrine.orm.naming_strategy.underscore
#            metadata_cache_driver:
#                type: memcache
#                host: "%memcached_host%"
#                port: "%memcached_port%"
#                instance_class: Memcached
#                class: Doctrine\Common\Cache\MemcacheCache
#            query_cache_driver:
#                type: memcache
#                host: "%memcached_host%"
#                port: "%memcached_port%"
#                instance_class: Memcached
#                class: Doctrine\Common\Cache\MemcacheCache
#            result_cache_driver:
#                type: memcache
#                host: "%memcached_host%"
#                port: "%memcached_port%"
#                instance_class: Memcached
#                class: Doctrine\Common\Cache\MemcacheCache
#            second_level_cache:
#                enabled:  true
#                log_enabled: true

#            mappings:
#                payments:
#                    type: annotation
#                    dir:  '%kernel.root_dir%/../src/Core/Payments/Domain/Model'
#                    prefix: Aptitus\Payments\Domain\Model
#                    alias: Payments
#                    is_bundle: false

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: App\Migrations
    table_name: migration_versions
    name: Application Migrations