# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    misa.inflector.service:
        class: Common\Service\MisaInflector
    misa.encrypt.service:
        class: Common\Service\EncryptService
        arguments: ['%app_secret%']
    misa.password.service:
        class: Common\Service\PasswordService