services:
#    persons.example:
#        class: Persons\Infrastructure\Ui\PersonsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    persons.person.list.srv:
        class: Persons\Domain\Services\Person\ListService
        arguments: ["@persons.person.rep"]
    persons.person.rep:
        class: Persons\Infrastructure\Persistence\Doctrine\PersonDbRepository
        arguments: ["@doctrine.orm.default_entity_manager", 'Persons\Domain\Entity\Person']

    persons.employee.rep:
        class: Persons\Infrastructure\Persistence\Doctrine\EmployeeDbRepository
        arguments: ["@doctrine.orm.default_entity_manager",'Persons\Domain\Entity\Employee']

    persons.employee.list.srv:
        class: Persons\Domain\Services\Employee\ListService
        arguments: ["@persons.employee.rep"]

    persons.employee.mng.srv:
        class: Persons\Domain\Services\Employee\MngService
        arguments: ["@persons.employee.rep","@misa.encrypt.service","@misa.password.service"]