<?php

namespace Persons\Domain\Repository;

/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
interface EmployeeRepository
{
}
