<?php

namespace Persons\Domain\Repository;

use Persons\Domain\Entity\Employee;

/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
interface EmployeeRepository
{
    /**
     * @param $employeeId
     * @return Employee
     */
    public function getById($employeeId);

    /**
     * @param $employeeId
     * @return array
     */
    public function findById($employeeId);

    /**
     * @param $filter
     * @return array
     */
    public function findAll($filter);

    /**
     * @param Employee $employee
     * @return bool
     */
    public function persist(Employee $employee);
}
