<?php

namespace Persons\Domain\Repository;

use Persons\Domain\Entity\Employee;
use Common\Adapter\Persistence\Doctrine\MisaRepository;
/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
interface EmployeeRepository extends MisaRepository
{

    /**
     * @param $employeeId
     * @return array
     */
    public function listById($employeeId);

    /**
     * @param $filter
     * @return array
     */
    public function listAll($filter);

    /**
     * @param Employee $employee
     * @return bool
     */
    public function persist(Employee $employee);
}
