<?php

namespace Persons\Domain\Repository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
interface PersonRepository
{
    /**
     * @param $filter
     * @return array
     */
    public function getAll($filter);
}
