<?php

namespace Persons\Domain\Repository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
interface PersonRepository
{
    /**
     * @param array $filter
     * @return array
     */
    public function findAll($filter);

    /**
     * @param string $personId
     * @return array
     */
    public function findById($personId);
}
