<?php

namespace Persons\Domain\Repository;
use Common\Adapter\Persistence\Doctrine\MisaRepository;
/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
interface PersonRepository extends MisaRepository
{
    /**
     * @param array $filter
     * @return array
     */
    public function listAll($filter);

    /**
     * @param string $personId
     * @return array
     */
    public function listById($personId);
}
